In [1]:
# Supress Warnings

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Import the numpy and pandas packages

import numpy as np
import pandas as pd

## Task 1: Reading and Inspection

-  ### Subtask 1.1: Import and read

Import and read the movie database. Store it in a variable called `movies`.

In [3]:
movies = pd.read_csv("Movie+Assignment+Data.csv")# Write your code for importing the csv file here
movies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000
10,Color,Zack Snyder,673.0,183.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,...,3018.0,English,USA,PG-13,250000000.0,2016.0,4000.0,6.9,2.35,197000
11,Color,Bryan Singer,434.0,169.0,0.0,903.0,Marlon Brando,18000.0,200069408.0,Action|Adventure|Sci-Fi,...,2367.0,English,USA,PG-13,209000000.0,2006.0,10000.0,6.1,2.35,0
12,Color,Marc Forster,403.0,106.0,395.0,393.0,Mathieu Amalric,451.0,168368427.0,Action|Adventure,...,1243.0,English,UK,PG-13,200000000.0,2008.0,412.0,6.7,2.35,0
13,Color,Gore Verbinski,313.0,151.0,563.0,1000.0,Orlando Bloom,40000.0,423032628.0,Action|Adventure|Fantasy,...,1832.0,English,USA,PG-13,225000000.0,2006.0,5000.0,7.3,2.35,5000
14,Color,Gore Verbinski,450.0,150.0,563.0,1000.0,Ruth Wilson,40000.0,89289910.0,Action|Adventure|Western,...,711.0,English,USA,PG-13,215000000.0,2013.0,2000.0,6.5,2.35,48000
15,Color,Zack Snyder,733.0,143.0,0.0,748.0,Christopher Meloni,15000.0,291021565.0,Action|Adventure|Fantasy|Sci-Fi,...,2536.0,English,USA,PG-13,225000000.0,2013.0,3000.0,7.2,2.35,118000
16,Color,Andrew Adamson,258.0,150.0,80.0,201.0,Pierfrancesco Favino,22000.0,141614023.0,Action|Adventure|Family|Fantasy,...,438.0,English,USA,PG,225000000.0,2008.0,216.0,6.6,2.35,0
17,Color,Joss Whedon,703.0,173.0,0.0,19000.0,Robert Downey Jr.,26000.0,623279547.0,Action|Adventure|Sci-Fi,...,1722.0,English,USA,PG-13,220000000.0,2012.0,21000.0,8.1,1.85,123000
18,Color,Rob Marshall,448.0,136.0,252.0,1000.0,Sam Claflin,40000.0,241063875.0,Action|Adventure|Fantasy,...,484.0,English,USA,PG-13,250000000.0,2011.0,11000.0,6.7,2.35,58000
19,Color,Barry Sonnenfeld,451.0,106.0,188.0,718.0,Michael Stuhlbarg,10000.0,179020854.0,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,...,341.0,English,USA,PG-13,225000000.0,2012.0,816.0,6.8,1.85,40000
20,Color,Peter Jackson,422.0,164.0,0.0,773.0,Adam Brown,5000.0,255108370.0,Adventure|Fantasy,...,802.0,English,New Zealand,PG-13,250000000.0,2014.0,972.0,7.5,2.35,65000
21,Color,Marc Webb,599.0,153.0,464.0,963.0,Andrew Garfield,15000.0,262030663.0,Action|Adventure|Fantasy,...,1225.0,English,USA,PG-13,230000000.0,2012.0,10000.0,7.0,2.35,56000
22,Color,Ridley Scott,343.0,156.0,0.0,738.0,William Hurt,891.0,105219735.0,Action|Adventure|Drama|History,...,546.0,English,USA,PG-13,200000000.0,2010.0,882.0,6.7,2.35,17000
23,Color,Peter Jackson,509.0,186.0,0.0,773.0,Adam Brown,5000.0,258355354.0,Adventure|Fantasy,...,951.0,English,USA,PG-13,225000000.0,2013.0,972.0,7.9,2.35,83000
24,Color,Chris Weitz,251.0,113.0,129.0,1000.0,Eva Green,16000.0,70083519.0,Adventure|Family|Fantasy,...,666.0,English,USA,PG-13,180000000.0,2007.0,6000.0,6.1,2.35,0
25,Color,Peter Jackson,446.0,201.0,0.0,84.0,Thomas Kretschmann,6000.0,218051260.0,Action|Adventure|Drama|Romance,...,2618.0,English,New Zealand,PG-13,207000000.0,2005.0,919.0,7.2,2.35,0
26,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,...,2528.0,English,USA,PG-13,200000000.0,1997.0,14000.0,7.7,2.35,26000
27,Color,Anthony Russo,516.0,147.0,94.0,11000.0,Scarlett Johansson,21000.0,407197282.0,Action|Adventure|Sci-Fi,...,1022.0,English,USA,PG-13,250000000.0,2016.0,19000.0,8.2,2.35,72000
28,Color,Peter Berg,377.0,131.0,532.0,627.0,Alexander Skarsgård,14000.0,65173160.0,Action|Adventure|Sci-Fi|Thriller,...,751.0,English,USA,PG-13,209000000.0,2012.0,10000.0,5.9,2.35,44000
29,Color,Colin Trevorrow,644.0,124.0,365.0,1000.0,Judy Greer,3000.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,...,1290.0,English,USA,PG-13,150000000.0,2015.0,2000.0,7.0,2.00,150000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5013,Color,Eric Eason,28.0,79.0,3.0,42.0,Panchito Gómez,93.0,NaN,Drama|Family,...,21.0,English,USA,NaN,24000.0,2002.0,46.0,7.0,1.78,61
5014,Color,Uwe Boll,58.0,80.0,892.0,492.0,Katharine Isabelle,986.0,NaN,Action|Crime|Thriller,...,129.0,English,Canada,R,NaN,2009.0,918.0,6.3,2.35,0
5015,Black and White,Richard Linklater,61.0,100.0,0.0,0.0,Richard Linklater,5.0,1227508.0,Comedy|Drama,...,80.0,English,USA,R,23000.0,1991.0,0.0,7.1,1.37,2000
5016,Color,Joseph Mazzella,NaN,90.0,0.0,9.0,Mikaal Bates,313.0,NaN,Crime|Drama|Thriller,...,2.0,English,USA,NaN,25000.0,2015.0,25.0,4.8,NaN,33
5017,Color,Travis Legge,1.0,90.0,138.0,138.0,Suzi Lorraine,370.0,NaN,Comedy|Romance,...,3.0,English,USA,NaN,22000.0,2013.0,184.0,3.3,1.78,200
5018,Color,Alex Kendrick,5.0,120.0,589.0,4.0,Lisa Arnold,51.0,NaN,Drama,...,49.0,English,USA,NaN,20000.0,2003.0,49.0,6.9,1.85,725
5019,Color,Marcus Nispel,43.0,91.0,158.0,265.0,Brittany Curran,630.0,NaN,Horror|Mystery|Thriller,...,33.0,English,USA,R,NaN,2015.0,512.0,4.6,1.85,0
5020,NaN,Brandon Landers,NaN,143.0,8.0,8.0,Alana Kaniewski,720.0,NaN,Drama|Horror|Thriller,...,8.0,English,USA,NaN,17350.0,2011.0,19.0,3.0,NaN,33
5021,Color,Jay Duplass,51.0,85.0,157.0,10.0,Katie Aselton,830.0,192467.0,Comedy|Drama|Romance,...,71.0,English,USA,R,15000.0,2005.0,224.0,6.6,NaN,297
5022,Black and White,Jim Chuchu,6.0,60.0,0.0,4.0,Olwenya Maina,147.0,NaN,Drama,...,1.0,Swahili,Kenya,NaN,15000.0,2014.0,19.0,7.4,NaN,45
5023,Color,Daryl Wein,22.0,88.0,38.0,211.0,Heather Burns,331.0,76382.0,Romance,...,8.0,English,USA,NaN,15000.0,2009.0,212.0,6.2,2.35,324
5024,Color,Jason Trost,42.0,78.0,91.0,86.0,Jason Trost,407.0,NaN,Sci-Fi|Thriller,...,35.0,English,USA,Unrated,20000.0,2011.0,91.0,4.0,2.35,835
5025,Color,John Waters,73.0,108.0,0.0,105.0,Mink Stole,462.0,180483.0,Comedy|Crime|Horror,...,183.0,English,USA,NC-17,10000.0,1972.0,143.0,6.1,1.37,0
5026,Color,Olivier Assayas,81.0,110.0,107.0,45.0,Béatrice Dalle,576.0,136007.0,Drama|Music|Romance,...,39.0,French,France,R,4500.0,2004.0,133.0,6.9,2.35,171
5027,Color,Jafar Panahi,64.0,90.0,397.0,0.0,Nargess Mamizadeh,5.0,673780.0,Drama,...,26.0,Persian,Iran,Not Rated,10000.0,2000.0,0.0,7.5,1.85,697
5028,Black and White,Ivan Kavanagh,12.0,83.0,18.0,0.0,Michael Parle,10.0,NaN,Horror,...,1.0,English,Ireland,NaN,10000.0,2007.0,5.0,6.7,1.33,105
5029,Color,Kiyoshi Kurosawa,78.0,111.0,62.0,6.0,Anna Nakagawa,89.0,94596.0,Crime|Horror|Mystery|Thriller,...,50.0,Japanese,Japan,NaN,1000000.0,1997.0,13.0,7.4,1.85,817
5030,Color,Tadeo Garcia,NaN,84.0,5.0,12.0,Michael Cortez,21.0,NaN,Drama,...,3.0,English,USA,NaN,NaN,2004.0,20.0,6.1,NaN,22
5031,Color,Thomas L. Phillips,13.0,82.0,120.0,84.0,Joe Coffey,785.0,NaN,Comedy|Horror|Thriller,...,8.0,English,USA,NaN,200000.0,2012.0,98.0,5.4,16.00,424
5032,Color,Ash Baron-Cohen,10.0,98.0,3.0,152.0,Stanley B. Herman,789.0,NaN,Crime|Drama,...,14.0,English,USA,NaN,NaN,1995.0,194.0,6.4,NaN,20
5033,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,371.0,English,USA,PG-13,7000.0,2004.0,45.0,7.0,1.85,19000
5034,Color,Neill Dela Llana,35.0,80.0,0.0,0.0,Edgar Tancangco,0.0,70071.0,Thriller,...,35.0,English,Philippines,Not Rated,7000.0,2005.0,0.0,6.3,NaN,74
5035,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.37,0
5036,Color,Anthony Vallone,NaN,84.0,2.0,2.0,John Considine,45.0,NaN,Crime|Drama,...,1.0,English,USA,PG-13,3250.0,2005.0,44.0,7.8,NaN,4
5037,Color,Edward Burns,14.0,95.0,0.0,133.0,Caitlin FitzGerald,296.0,4584.0,Comedy|Drama,...,14.0,English,USA,Not Rated,9000.0,2011.0,205.0,6.4,NaN,413
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

-  ### Subtask 1.2: Inspect the dataframe

Inspect the dataframe's columns, shapes, variable types etc.

In [4]:
# Write your code for inspection here
movies.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [5]:
movies.shape

(5043, 28)

In [6]:
movies.dtypes

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

In [7]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
color                        5024 non-null object
director_name                4939 non-null object
num_critic_for_reviews       4993 non-null float64
duration                     5028 non-null float64
director_facebook_likes      4939 non-null float64
actor_3_facebook_likes       5020 non-null float64
actor_2_name                 5030 non-null object
actor_1_facebook_likes       5036 non-null float64
gross                        4159 non-null float64
genres                       5043 non-null object
actor_1_name                 5036 non-null object
movie_title                  5043 non-null object
num_voted_users              5043 non-null int64
cast_total_facebook_likes    5043 non-null int64
actor_3_name                 5020 non-null object
facenumber_in_poster         5030 non-null float64
plot_keywords                4890 non-null object
movie_imdb_link              5043 non-null object
num_user_for_reviews         5022 non-null float64
language                     5031 non-null object
country                      5038 non-null object
content_rating               4740 non-null object
budget                       4551 non-null float64
title_year                   4935 non-null float64
actor_2_facebook_likes       5030 non-null float64
imdb_score                   5043 non-null float64
aspect_ratio                 4714 non-null float64
movie_facebook_likes         5043 non-null int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [8]:
movies.describe() #it shows Description all numeric columns with mean, median, Standard Deviation

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4993.000000,5028.000000,4939.000000,5020.000000,5036.000000,4.159000e+03,5.043000e+03,5043.000000,5030.000000,5022.000000,4.551000e+03,4935.000000,5030.000000,5043.000000,4714.000000,5043.000000
mean,140.194272,107.201074,686.509212,645.009761,6560.047061,4.846841e+07,8.366816e+04,9699.063851,1.371173,272.770808,3.975262e+07,2002.470517,1651.754473,6.442138,2.220403,7525.964505
std,121.601675,25.197441,2813.328607,1665.041728,15020.759120,6.845299e+07,1.384853e+05,18163.799124,2.013576,377.982886,2.061149e+08,12.474599,4042.438863,1.125116,1.385113,19320.445110
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
25%,50.000000,93.000000,7.000000,133.000000,614.000000,5.340988e+06,8.593500e+03,1411.000000,0.000000,65.000000,6.000000e+06,1999.000000,281.000000,5.800000,1.850000,0.000000
50%,110.000000,103.000000,49.000000,371.500000,988.000000,2.551750e+07,3.435900e+04,3090.000000,1.000000,156.000000,2.000000e+07,2005.000000,595.000000,6.600000,2.350000,166.000000
75%,195.000000,118.000000,194.500000,636.000000,11000.000000,6.230944e+07,9.630900e+04,13756.500000,2.000000,326.000000,4.500000e+07,2011.000000,918.000000,7.200000,2.350000,3000.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,1.221550e+10,2016.000000,137000.000000,9.500000,16.000000,349000.000000

In [9]:
movies.describe(include=['object']) #It will Object type Columns Description with count, top, Unique element and frequency

,color,director_name,actor_2_name,genres,actor_1_name,movie_title,actor_3_name,plot_keywords,movie_imdb_link,language,country,content_rating
count,5024,4939,5030,5043,5036,5043,5020,4890,5043,5031,5038,4740
unique,2,2398,3032,914,2097,4917,3521,4760,4919,47,65,18
top,Color,Steven Spielberg,Morgan Freeman,Drama,Robert De Niro,Victor Frankenstein,Steve Coogan,based on novel,http://www.imdb.com/title/tt2224026/?ref_=fn_t...,English,USA,R
freq,4815,26,20,236,49,3,8,4,3,4704,3807,2118

## Task 2: Cleaning the Data

-  ### Subtask 2.1: Inspect Null values

Find out the number of Null values in all the columns and rows. Also, find the percentage of Null values in each column. Round off the percentages upto two decimal places.

In [10]:
# Write your code for column-wise null count here
movies.isnull().sum() #by default axis parameter is 0 in sum(), it count rows in columns

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [11]:
# Write your code for row-wise null count here
movies.isnull().sum(axis=1) #by assigning axis parameter to 1 in sum(), it count columns in rows

0        0
1        0
2        0
3        0
4       14
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
5013     2
5014     2
5015     0
5016     5
5017     2
5018     2
5019     2
5020     5
5021     1
5022     4
5023     2
5024     1
5025     0
5026     0
5027     0
5028     3
5029     1
5030     5
5031     3
5032     4
5033     0
5034     1
5035     0
5036     3
5037     1
5038     4
5039     5
5040     4
5041     2
5042     0
Length: 5043, dtype: int64

In [12]:
# Write your code for column-wise null percentages here
round((movies.isnull().sum()/len(movies))*100,2)

color                         0.38
director_name                 2.06
num_critic_for_reviews        0.99
duration                      0.30
director_facebook_likes       2.06
actor_3_facebook_likes        0.46
actor_2_name                  0.26
actor_1_facebook_likes        0.14
gross                        17.53
genres                        0.00
actor_1_name                  0.14
movie_title                   0.00
num_voted_users               0.00
cast_total_facebook_likes     0.00
actor_3_name                  0.46
facenumber_in_poster          0.26
plot_keywords                 3.03
movie_imdb_link               0.00
num_user_for_reviews          0.42
language                      0.24
country                       0.10
content_rating                6.01
budget                        9.76
title_year                    2.14
actor_2_facebook_likes        0.26
imdb_score                    0.00
aspect_ratio                  6.52
movie_facebook_likes          0.00
dtype: float64

-  ### Subtask 2.2: Drop unecessary columns

For this assignment, you will mostly be analyzing the movies with respect to the ratings, gross collection, popularity of movies, etc. So many of the columns in this dataframe are not required. So it is advised to drop the following columns.
-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords

In [13]:
# Write your code for dropping the columns here. It is advised to keep inspecting the dataframe after each set of operations 
unnecessary_col_list = ['color','director_facebook_likes','actor_1_facebook_likes','actor_2_facebook_likes','actor_3_facebook_likes','actor_2_name','cast_total_facebook_likes','actor_3_name','duration','facenumber_in_poster','content_rating','country','movie_imdb_link','aspect_ratio','plot_keywords',]
movies.drop(unnecessary_col_list,axis = 1,inplace = True) #passing unneessary list to drop() at a time, to drop all columns with axis=1
movies.shape

(5043, 13)

-  ### Subtask 2.3: Drop unecessary rows using columns with high Null percentages

Now, on inspection you might notice that some columns have large percentage (greater than 5%) of Null values. Drop all the rows which have Null values for such columns.

In [14]:
# Write your code for dropping the rows here
cols_Null_Per = ((movies.isnull().sum()/len(movies))*100) # Calculating Column Null Percentage and Assigning to new varible
High_Null_Per_Cols = list(cols_Null_Per[cols_Null_Per>5].index) # Getting high null Percentage columns into new list
movies.dropna(subset = High_Null_Per_Cols, inplace = True) #Checing on that highPercent Columns and Dropping if null
movies.shape

(3891, 13)

-  ### Subtask 2.4: Drop unecessary rows

Some of the rows might have greater than five NaN values. Such rows aren't of much use for the analysis and hence, should be removed.

In [15]:
# Write your code for dropping the rows here
#movies = movies.loc[movies.isnull().sum(axis = 1) <= 5,]
movies.dropna(thresh = 5,inplace = True) #Dropping rows(by default dropna checks rowwise)having minimun NULL values is 5
movies.shape

(3891, 13)

### Subtask 2.5: Fill NaN values

You might notice that the `language` column has some NaN values. Here, on inspection, you will see that it is safe to replace all the missing values with `'English'`.

In [16]:
# Write your code for filling the NaN values in the 'language' column heremovies['language'] = 
print(movies['language'].isnull().sum())
movies['language'] = movies['language'].fillna('English') #Filling 'na' value cells with 'English' value in language Column
print(movies['language'].isnull().sum())

3
0

  ### Subtask 2.6: Check the number of retained rows

You might notice that two of the columns viz. `num_critic_for_reviews` and `actor_1_name` have small percentages of NaN values left. You can let these columns as it is for now. Check the number and percentage of the rows retained after completing all the tasks above.

In [17]:
# Write your code for checking number of retained rows here
movies.info() #shows some NaN values in some cells
print("Retained rows",len(movies)) # Showing current rows
int((len(movies)/5043)*100) # As we have calucated rows in 1.2 task it shows 5043, so dividing present with 5043 gives Percentage

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3891 entries, 0 to 5042
Data columns (total 13 columns):
director_name             3891 non-null object
num_critic_for_reviews    3890 non-null float64
gross                     3891 non-null float64
genres                    3891 non-null object
actor_1_name              3888 non-null object
movie_title               3891 non-null object
num_voted_users           3891 non-null int64
num_user_for_reviews      3891 non-null float64
language                  3891 non-null object
budget                    3891 non-null float64
title_year                3891 non-null float64
imdb_score                3891 non-null float64
movie_facebook_likes      3891 non-null int64
dtypes: float64(6), int64(2), object(5)
memory usage: 425.6+ KB
Retained rows 3891

77

**Checkpoint 1:** You might have noticed that we still have around `77%` of the rows!

## Task 3: Data Analysis

-  ### Subtask 3.1: Change the unit of columns

Convert the unit of the `budget` and `gross` columns from `$` to `million $`.

In [18]:
# Write your code for unit conversion here
movies['budget'] = movies['budget']*(10**-6) #Converting budget column into million dollars by multiplying with 1/1000000
movies['gross'] = movies['gross']*(10**-6)
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0000,2009.0,7.9,33000
1,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300.0000,2007.0,7.1,0
2,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245.0000,2015.0,6.8,85000
3,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250.0000,2012.0,8.5,164000
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.7000,2012.0,6.6,24000
6,Sam Raimi,392.0,336.530303,Action|Adventure|Romance,J.K. Simmons,Spider-Man 3,383056,1902.0,English,258.0000,2007.0,6.2,0
7,Nathan Greno,324.0,200.807262,Adventure|Animation|Comedy|Family|Fantasy|Musi...,Brad Garrett,Tangled,294810,387.0,English,260.0000,2010.0,7.8,29000
8,Joss Whedon,635.0,458.991599,Action|Adventure|Sci-Fi,Chris Hemsworth,Avengers: Age of Ultron,462669,1117.0,English,250.0000,2015.0,7.5,118000
9,David Yates,375.0,301.956980,Adventure|Family|Fantasy|Mystery,Alan Rickman,Harry Potter and the Half-Blood Prince,321795,973.0,English,250.0000,2009.0,7.5,10000
10,Zack Snyder,673.0,330.249062,Action|Adventure|Sci-Fi,Henry Cavill,Batman v Superman: Dawn of Justice,371639,3018.0,English,250.0000,2016.0,6.9,197000
11,Bryan Singer,434.0,200.069408,Action|Adventure|Sci-Fi,Kevin Spacey,Superman Returns,240396,2367.0,English,209.0000,2006.0,6.1,0
12,Marc Forster,403.0,168.368427,Action|Adventure,Giancarlo Giannini,Quantum of Solace,330784,1243.0,English,200.0000,2008.0,6.7,0
13,Gore Verbinski,313.0,423.032628,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: Dead Man's Chest,522040,1832.0,English,225.0000,2006.0,7.3,5000
14,Gore Verbinski,450.0,89.289910,Action|Adventure|Western,Johnny Depp,The Lone Ranger,181792,711.0,English,215.0000,2013.0,6.5,48000
15,Zack Snyder,733.0,291.021565,Action|Adventure|Fantasy|Sci-Fi,Henry Cavill,Man of Steel,548573,2536.0,English,225.0000,2013.0,7.2,118000
16,Andrew Adamson,258.0,141.614023,Action|Adventure|Family|Fantasy,Peter Dinklage,The Chronicles of Narnia: Prince Caspian,149922,438.0,English,225.0000,2008.0,6.6,0
17,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0000,2012.0,8.1,123000
18,Rob Marshall,448.0,241.063875,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: On Stranger Tides,370704,484.0,English,250.0000,2011.0,6.7,58000
19,Barry Sonnenfeld,451.0,179.020854,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,Will Smith,Men in Black 3,268154,341.0,English,225.0000,2012.0,6.8,40000
20,Peter Jackson,422.0,255.108370,Adventure|Fantasy,Aidan Turner,The Hobbit: The Battle of the Five Armies,354228,802.0,English,250.0000,2014.0,7.5,65000
21,Marc Webb,599.0,262.030663,Action|Adventure|Fantasy,Emma Stone,The Amazing Spider-Man,451803,1225.0,English,230.0000,2012.0,7.0,56000
22,Ridley Scott,343.0,105.219735,Action|Adventure|Drama|History,Mark Addy,Robin Hood,211765,546.0,English,200.0000,2010.0,6.7,17000
23,Peter Jackson,509.0,258.355354,Adventure|Fantasy,Aidan Turner,The Hobbit: The Desolation of Smaug,483540,951.0,English,225.0000,2013.0,7.9,83000
24,Chris Weitz,251.0,70.083519,Adventure|Family|Fantasy,Christopher Lee,The Golden Compass,149019,666.0,English,180.0000,2007.0,6.1,0
25,Peter Jackson,446.0,218.051260,Action|Adventure|Drama|Romance,Naomi Watts,King Kong,316018,2618.0,English,207.0000,2005.0,7.2,0
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0000,1997.0,7.7,26000
27,Anthony Russo,516.0,407.197282,Action|Adventure|Sci-Fi,Robert Downey Jr.,Captain America: Civil War,272670,1022.0,English,250.0000,2016.0,8.2,72000
28,Peter Berg,377.0,65.173160,Action|Adventure|Sci-Fi|Thriller,Liam Neeson,Battleship,202382,751.0,English,209.0000,2012.0,5.9,44000
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0000,2015.0,7.0,150000
30,Sam Mendes,750.0,304.360277,Action|Adventure|Thriller,Albert Finney,Skyfall,522030,1498.0,English,200.0000,2012.0,7.8,80000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4959,Robert Townsend,21.0,5.228617,Comedy,Robert Townsend,Hollywood Shuffle,2770,32.0,English,0.1000,1987.0,7.0,471
4962,Larry Blamire,88.0,0.110536,Comedy|Horror|Sci-Fi,Fay Masterson,The Lost Skeleton of Cadavra,4117,118.0,English,0.0400,2001.0,7.0,0
4964,E.L. Katz,193.0,0.059379,Comedy|Crime|Drama|Horror|Thriller,Brighton Sharbino,Cheap Thrills,12796,52.0,English,0.2000,2013.0,6.8,0
4971,Dennis Iliadis,241.0,32.721635,Crime|Horror|Thriller,Tony Goldwyn,The Last House on the Left,67824,279.0,English,15.0000,2009.0,6.6,0
4973,Darren Aronofsky,138.0,3.216970,Drama|Mystery|Thriller,Mark Margolis,Pi,142619,586.0,English,0.0600,1998.0,7.5,24000
4975,Myles Berkowitz,32.0,0.536767,Biography|Comedy|Romance,Tia Carrere,20 Dates,1622,83.0,English,0.0600,1998.0,5.3,30
4977,Morgan Spurlock,193.0,11.529368,Comedy|Documentary|Drama,Chemeeka Walker,Super Size Me,85028,404.0,English,0.0650,2004.0,7.3,0
4978,Brandon Trost,66.0,0.040557,Comedy,Clifton Collins Jr.,The FP,1389,22.0,English,0.0600,2011.0,5.6,0
4979,Joe Swanberg,65.0,0.030084,Comedy|Drama,Anna Kendrick,Happy Christmas,5507,23.0,English,0.0700,2014.0,5.6,812
4984,Edward Burns,36.0,10.246600,Comedy|Drama|Romance,Shari Albert,The Brothers McMullen,6375,36.0,English,0.0250,1995.0,6.6,265
4987,Lena Dunham,113.0,0.389804,Comedy|Drama|Romance,Lena Dunham,Tiny Furniture,11816,35.0,English,0.0650,2010.0,6.3,0
4997,David Gordon Green,75.0,0.241816,Drama,Paul Schneider,George Washington,6246,76.0,English,0.0420,2000.0,7.5,451
4998,Kevin Jordan,21.0,0.277233,Comedy|Romance,Derick Martini,Smiling Fish & Goat on Fire,2631,26.0,English,0.0400,1999.0,7.6,0
5004,Mike Bruce,3.0,0.243768,Western,Joseph Campanella,The Legend of God's Gun,143,9.0,English,0.0300,2007.0,4.1,13
5008,Kevin Smith,136.0,3.151130,Comedy,Jason Mewes,Clerks,181749,615.0,English,0.2300,1994.0,7.8,0
5009,James Bidgood,8.0,0.008231,Drama|Fantasy,Don Brooks,Pink Narcissus,803,16.0,English,0.0270,1971.0,6.7,85
5011,Neil LaBute,80.0,2.856622,Comedy|Drama,Stacy Edwards,In the Company of Men,11550,197.0,English,0.0250,1997.0,7.3,489
5012,David Ayer,233.0,10.499968,Action|Crime|Drama|Thriller,Mireille Enos,Sabotage,47502,212.0,English,35.0000,2014.0,5.7,10000
5015,Richard Linklater,61.0,1.227508,Comedy|Drama,Tommy Pallotta,Slacker,15103,80.0,English,0.0230,1991.0,7.1,2000
5021,Jay Duplass,51.0,0.192467,Comedy|Drama|Romance,Mark Duplass,The Puffy Chair,4067,71.0,English,0.0150,2005.0,6.6,297
5023,Daryl Wein,22.0,0.076382,Romance,Zoe Lister-Jones,Breaking Upwards,1194,8.0,English,0.0150,2009.0,6.2,324
5025,John Waters,73.0,0.180483,Comedy|Crime|Horror,Divine,Pink Flamingos,16792,183.0,English,0.0100,1972.0,6.1,0
5026,Olivier Assayas,81.0,0.136007,Drama|Music|Romance,Maggie Cheung,Clean,3924,39.0,French,0.0045,2004.0,6.9,171
5027,Jafar Panahi,64.0,0.673780,Drama,Fereshteh Sadre Orafaiy,The Circle,4555,26.0,Persian,0.0100,2000.0,7.5,697
5029,Kiyoshi Kurosawa,78.0,0.094596,Crime|Horror|Mystery|Thriller,Kôji Yakusho,The Cure,6318,50.0,Japanese,1.0000,1997.0,7.4,817
5033,Shane Carruth,143.0,0.424760,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,0.0070,2004.0,7.0,19000
5034,Neill Dela Llana,35.0,0.070071,Thriller,Ian Gamazon,Cavite,589,35.0,English,0.0070,2005.0,6.3,74
5035,Robert Rodriguez,56.0,2.040920,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,0.0070,1992.0,6.9,0
5037,Edward Burns,14.0,0.004584,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14.0,English,0.0090,2011.0,6.4,413
5042,Jon Gunn,43.0,0.085222,Documentary,John August,My Date with Drew,4285,84.0,English,0.0011,2004.0,6.6,456

-  ### Subtask 3.2: Find the movies with highest profit

    1. Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
    2. Sort the dataframe using the `profit` column as reference.
    3. Extract the top ten profiting movies in descending order and store them in a new dataframe - `top10`

In [19]:
# Write your code for creating the profit column here
movies['profit'] = movies['gross']-movies['budget'] # creating profit column by subtracting gross,budget columns

In [20]:
# Write your code for sorting the dataframe here
movies.sort_values(by = 'profit',ascending = False,inplace = True) #sorting data set as descending order on basis of profit

In [21]:
# Write your code to get the top 10 profiting movies here
top10 = movies.head(10) # here head() will assign first 10 rows to top10 variable
top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.5,1982.0,7.9,34000,424.449459
794,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
17,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
509,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.0,1994.0,8.5,17000,377.783777
240,George Lucas,320.0,474.544677,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.0,1999.0,6.5,13000,359.544677
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.316061

-  ### Subtask 3.3: Drop duplicate values

After you found out the top 10 profiting movies, you might have notice a duplicate value. So, it seems like the dataframe has duplicate values as well. Drop the duplicate values from the dataframe and repeat `Subtask 3.2`.

In [22]:
# Write your code for dropping duplicate values here
movies.drop_duplicates(inplace = True) #drop_duplicates values by checing all columns(by default, without passing parameter for this)

In [23]:
# Write code for repeating subtask 2 here
top10 = movies.head(10) #After droping again getting top 10 rows
top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.5,1982.0,7.9,34000,424.449459
794,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
509,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.0,1994.0,8.5,17000,377.783777
240,George Lucas,320.0,474.544677,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.0,1999.0,6.5,13000,359.544677
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.316061
439,Gary Ross,673.0,407.999255,Adventure|Drama|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games,701607,1959.0,English,78.0,2012.0,7.3,140000,329.999255

**Checkpoint 2:** You might spot two movies directed by `James Cameron` in the list.

-  ### Subtask 3.4: Find IMDb Top 250

    1. Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Also make sure that for all of these movies, the `num_voted_users` is greater than 25,000.
Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.
    2. Extract all the movies in the `IMDb_Top_250` dataframe which are not in the English language and store them in a new dataframe named `Top_Foreign_Lang_Film`.

In [24]:
# Write your code for extracting the top 250 movies as per the IMDb score here. Make sure that you store it in a new dataframe 
# and name that dataframe as 'IMDb_Top_250'

IMDb_Top_250 = movies[movies.num_voted_users > 25000].sort_values(by = 'imdb_score',ascending = False,inplace = False).head(250)
#By making condition for Voted_users > 25000, on this sorting descending order by 'imbd_score' and gettind first 250 rows using head(250)

IMDb_Top_250.insert(0,'Rank',np.arange(1,251)) #Insering rank column in 0th index with ranks 1-250
IMDb_Top_250

,Rank,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
1937,1,Frank Darabont,199.0,28.341469,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144.0,English,25.00,1994.0,9.3,108000,3.341469
3466,2,Francis Ford Coppola,208.0,134.821952,Crime|Drama,Al Pacino,The Godfather,1155770,2238.0,English,6.00,1972.0,9.2,43000,128.821952
2837,3,Francis Ford Coppola,149.0,57.300000,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650.0,English,13.00,1974.0,9.0,14000,44.300000
66,4,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.00,2008.0,9.0,37000,348.316061
339,5,Peter Jackson,328.0,377.019252,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the King,1215718,3189.0,English,94.00,2003.0,8.9,16000,283.019252
1874,6,Steven Spielberg,174.0,96.067179,Biography|Drama|History,Liam Neeson,Schindler's List,865020,1273.0,English,22.00,1993.0,8.9,41000,74.067179
4498,7,Sergio Leone,181.0,6.100000,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.20,1966.0,8.9,20000,4.900000
3355,8,Quentin Tarantino,215.0,107.930000,Crime|Drama,Bruce Willis,Pulp Fiction,1324680,2195.0,English,8.00,1994.0,8.9,45000,99.930000
97,9,Christopher Nolan,642.0,292.568851,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,160.00,2010.0,8.8,175000,132.568851
683,10,David Fincher,315.0,37.023395,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,63.00,1999.0,8.8,48000,-25.976605
2051,11,Irvin Kershner,223.0,290.158751,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode V - The Empire Strikes Back,837759,900.0,English,18.00,1980.0,8.8,17000,272.158751
836,12,Robert Zemeckis,149.0,329.691196,Comedy|Drama,Tom Hanks,Forrest Gump,1251222,1398.0,English,55.00,1994.0,8.8,59000,274.691196
270,13,Peter Jackson,297.0,313.837577,Action|Adventure|Drama|Fantasy,Christopher Lee,The Lord of the Rings: The Fellowship of the R...,1238746,5060.0,English,93.00,2001.0,8.8,21000,220.837577
3867,14,Milos Forman,149.0,112.000000,Drama,Scatman Crothers,One Flew Over the Cuckoo's Nest,680041,760.0,English,4.40,1975.0,8.7,32000,107.600000
4029,15,Fernando Meirelles,214.0,7.563397,Crime|Drama,Alice Braga,City of God,533200,749.0,Portuguese,3.30,2002.0,8.7,28000,4.263397
3024,16,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.00,1977.0,8.7,33000,449.935665
4747,17,Akira Kurosawa,153.0,0.269061,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596.0,Japanese,2.00,1954.0,8.7,11000,-1.730939
340,18,Peter Jackson,294.0,340.478898,Action|Adventure|Drama|Fantasy,Christopher Lee,The Lord of the Rings: The Two Towers,1100446,2417.0,English,94.00,2002.0,8.7,10000,246.478898
1903,19,Martin Scorsese,192.0,46.836394,Biography|Crime|Drama,Robert De Niro,Goodfellas,728685,989.0,English,25.00,1990.0,8.7,25000,21.836394
654,20,Lana Wachowski,313.0,171.383253,Action|Sci-Fi,Keanu Reeves,The Matrix,1217752,3646.0,English,63.00,1999.0,8.7,25000,108.383253
2158,21,Jonathan Demme,185.0,130.727000,Crime|Drama|Horror|Thriller,Anthony Hopkins,The Silence of the Lambs,887467,916.0,English,19.00,1991.0,8.6,40000,111.727000
4427,22,Charles Chaplin,120.0,0.163245,Comedy|Drama|Family,Paulette Goddard,Modern Times,143086,211.0,English,1.50,1936.0,8.6,0,-1.336755
3175,23,Tony Kaye,162.0,6.712241,Crime|Drama,Ethan Suplee,American History X,782437,1420.0,English,7.50,1998.0,8.6,35000,-0.787759
648,24,Steven Spielberg,219.0,216.119491,Action|Drama|War,Tom Hanks,Saving Private Ryan,881236,2277.0,English,70.00,1998.0,8.6,22000,146.119491
3592,25,Bryan Singer,162.0,23.272306,Crime|Drama|Mystery|Thriller,Kevin Spacey,The Usual Suspects,740918,1182.0,English,6.00,1995.0,8.6,28000,17.272306
2373,26,Hayao Miyazaki,246.0,10.049886,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902.0,Japanese,19.00,2001.0,8.6,28000,-8.950114
1600,27,David Fincher,216.0,100.125340,Crime|Drama|Mystery|Thriller,Morgan Freeman,Se7en,1023511,1080.0,English,33.00,1995.0,8.6,39000,67.125340
96,28,Christopher Nolan,712.0,187.991439,Adventure|Drama|Sci-Fi,Matthew McConaughey,Interstellar,928227,2725.0,English,165.00,2014.0,8.6,349000,22.991439
283,29,Ridley Scott,265.0,187.670866,Action|Drama|Romance,Djimon Hounsou,Gladiator,982637,2368.0,English,103.00,2000.0,8.5,21000,84.670866
1571,30,Francis Ford Coppola,261.0,78.800000,Drama|War,Harrison Ford,Apocalypse Now,450676,983.0,English,31.50,1979.0,8.5,19000,47.300000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353,221,John Lasseter,191.0,245.823397,Adventure|Animation|Comedy|Family|Fantasy,Tom Hanks,Toy Story 2,385871,515.0,English,90.00,1999.0,7.9,0,155.823397
1807,222,John Landis,125.0,54.200000,Action|Comedy|Crime|Music,John Belushi,The Blues Brothers,142448,319.0,English,27.00,1980.0,7.9,14000,27.200000
3357,223,Dan Gilroy,534.0,32.279955,Crime|Drama|Thriller,Jake Gyllenhaal,Nightcrawler,293304,552.0,English,8.50,2014.0,7.9,65000,23.779955
2418,224,Edward Zwick,60.0,26.830000,Drama|History|War,Denzel Washington,Glory,101889,365.0,English,18.00,1989.0,7.9,0,8.830000
1735,225,James Mangold,291.0,119.518352,Biography|Drama|Music|Romance,Sandra Ellis Lafferty,Walk the Line,188637,815.0,English,28.00,2005.0,7.9,11000,91.518352
1713,226,Edward Zwick,60.0,26.830000,Drama|History|War,Denzel Washington,Glory,101888,365.0,English,18.00,1989.0,7.9,0,8.830000
3510,227,Yash Chopra,29.0,2.921738,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119.0,Hindi,7.00,2004.0,7.9,2000,-4.078262
69,228,Jon Favreau,486.0,318.298180,Action|Adventure|Sci-Fi,Robert Downey Jr.,Iron Man,696338,1055.0,English,140.00,2008.0,7.9,10000,178.298180
0,229,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.00,2009.0,7.9,33000,523.505847
3452,230,Paul Haggis,287.0,54.557348,Crime|Drama|Thriller,Don Cheadle,Crash,361169,1624.0,English,6.50,2004.0,7.9,18000,48.057348
927,231,Andrew Adamson,212.0,267.652016,Adventure|Animation|Comedy|Family|Fantasy,Kathleen Freeman,Shrek,467113,945.0,English,60.00,2001.0,7.9,0,207.652016
162,232,Dean DeBlois,292.0,176.997107,Action|Adventure|Animation|Comedy|Family|Fantasy,Gerard Butler,How to Train Your Dragon 2,221128,343.0,English,145.00,2014.0,7.9,46000,31.997107
3080,233,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.50,1982.0,7.9,34000,424.449459
2449,234,Tim Burton,148.0,5.887457,Biography|Comedy|Drama,Johnny Depp,Ed Wood,142416,420.0,English,18.00,1994.0,7.9,0,-12.112543
3768,235,Duncan Jones,415.0,5.009677,Drama|Mystery|Sci-Fi,Kevin Spacey,Moon,260607,485.0,English,5.00,2009.0,7.9,47000,0.009677
1871,236,Pierre Morel,309.0,145.000989,Action|Thriller,Liam Neeson,Taken,483756,974.0,English,25.00,2008.0,7.9,29000,120.000989
99,237,Peter Jackson,645.0,303.001229,Adventure|Fantasy,Aidan Turner,The Hobbit: An Unexpected Journey,637246,1367.0,English,180.00,2012.0,7.9,166000,123.001229
4415,238,Fabián Bielinsky,94.0,1.221261,Crime|Drama|Thriller,Ricardo Darín,Nine Queens,38215,125.0,Spanish,1.50,2000.0,7.9,0,-0.278739
23,239,Peter Jackson,509.0,258.355354,Adventure|Fantasy,Aidan Turner,The Hobbit: The Desolation of Smaug,483540,951.0,English,225.00,2013.0,7.9,83000,33.355354
2177,240,Tim Burton,111.0,56.362352,Fantasy|Romance,Johnny Depp,Edward Scissorhands,357581,588.0,English,20.00,1990.0,7.9,16000,36.362352
3677,241,Christophe Barratier,112.0,3.629758,Drama|Music,Jean-Baptiste Maunier,The Chorus,44151,110.0,French,5.50,2004.0,7.9,0,-1.870242
2493,242,Yimou Zhang,283.0,0.084961,Action|Adventure|History,Jet Li,Hero,149414,841.0,Mandarin,31.00,2002.0,7.9,0,-30.915039
1748,243,F. Gary Gray,349.0,161.029270,Biography|Crime|Drama|History|Music,Aldis Hodge,Straight Outta Compton,119928,331.0,English,28.00,2015.0,7.9,76000,133.029270
3595,244,Darren Aronofsky,391.0,26.236603,Drama|Sport,Mark Margolis,The Wrestler,251349,547.0,English,6.00,2008.0,7.9,10000,20.236603
2558,245,Edgar Wright,285.0,23.618786,Action|Comedy|Mystery,Bill Bailey,Hot Fuzz,352695,687.0,English,8.00,2007.0,7.9,17000,15.618786
4640,246,Cristian Mungiu,233.0,1.185783,Drama,Anamaria Marinca,"4 Months, 3 Weeks and 2 Days",44763,172.0,Romanian,0.59,2007.0,7.9,14000,0.595783
2492,247,John Carpenter,318.0,47.000000,Horror|Thriller,Jamie Lee Curtis,Halloween,157857,1191.0,English,0.30,1978.0,7.9,12000,46.700000
4821,248,John Carpenter,318.0,47.000000,Horror|Thriller,Jamie Lee Curtis,Halloween,157863,1191.0,English,0.30,1978.0,7.9,12000,46.700000
639,249,Michael Mann,209.0,28.965197,Biography|Drama|Thriller,Al Pacino,The Insider,133526,521.0,English,68.00,1999.0,7.9,0,-39.034803
3029,250,David O. Russell,410.0,93.571803,Biography|Drama|Sport,Christian Bale,The Fighter,275869,389.0,English,25.00,2010.0,7.9,36000,68.571803

In [25]:
# Write your code to extract top foreign language films from 'IMDb_Top_250' here
Top_Foreign_Lang_Film = IMDb_Top_250[IMDb_Top_250.language != 'English'] 
#Getting movies which are not in english language by indexing and assigning to new varible
Top_Foreign_Lang_Film

,Rank,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
4498,7,Sergio Leone,181.0,6.100000,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.200000,1966.0,8.9,20000,4.900000
4029,15,Fernando Meirelles,214.0,7.563397,Crime|Drama,Alice Braga,City of God,533200,749.0,Portuguese,3.300000,2002.0,8.7,28000,4.263397
4747,17,Akira Kurosawa,153.0,0.269061,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596.0,Japanese,2.000000,1954.0,8.7,11000,-1.730939
2373,26,Hayao Miyazaki,246.0,10.049886,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902.0,Japanese,19.000000,2001.0,8.6,28000,-8.950114
4921,43,Majid Majidi,46.0,0.925402,Drama|Family,Bahare Seddiqi,Children of Heaven,27882,130.0,Persian,0.180000,1997.0,8.5,0,0.745402
4259,46,Florian Henckel von Donnersmarck,215.0,11.284657,Drama|Thriller,Sebastian Koch,The Lives of Others,259379,407.0,German,2.000000,2006.0,8.5,39000,9.284657
1329,47,S.S. Rajamouli,44.0,6.498000,Action|Adventure|Drama|Fantasy|War,Tamannaah Bhatia,Baahubali: The Beginning,62756,410.0,Telugu,18.026148,2015.0,8.4,21000,-11.528148
4659,49,Asghar Farhadi,354.0,7.098492,Drama|Mystery,Shahab Hosseini,A Separation,151812,264.0,Persian,0.500000,2011.0,8.4,48000,6.598492
1298,52,Jean-Pierre Jeunet,242.0,33.201661,Comedy|Romance,Mathieu Kassovitz,Amélie,534262,1314.0,French,77.000000,2001.0,8.4,39000,-43.798339
4105,57,Chan-wook Park,305.0,2.181290,Drama|Mystery|Thriller,Min-sik Choi,Oldboy,356181,809.0,Korean,3.000000,2003.0,8.4,43000,-0.818710
2323,58,Hayao Miyazaki,174.0,2.298191,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2400.000000,1997.0,8.4,11000,-2397.701809
2970,60,Wolfgang Petersen,96.0,11.433134,Adventure|Drama|Thriller|War,Jürgen Prochnow,Das Boot,168203,426.0,German,14.000000,1981.0,8.4,11000,-2.566866
2734,68,Fritz Lang,260.0,0.026435,Drama|Sci-Fi,Brigitte Helm,Metropolis,111841,413.0,German,6.000000,1927.0,8.3,12000,-5.973565
4033,70,Thomas Vinterberg,349.0,0.610968,Drama,Thomas Bo Larsen,The Hunt,170155,249.0,Danish,3.800000,2012.0,8.3,60000,-3.189032
2829,74,Oliver Hirschbiegel,192.0,5.501940,Biography|Drama|History|War,Thomas Kretschmann,Downfall,248354,564.0,German,13.500000,2004.0,8.3,14000,-7.998060
3550,88,Denis Villeneuve,226.0,6.857096,Drama|Mystery|War,Lubna Azabal,Incendies,80429,156.0,French,6.800000,2010.0,8.2,37000,0.057096
4000,96,Juan José Campanella,262.0,20.167424,Drama|Mystery|Thriller,Ricardo Darín,The Secret in Their Eyes,131831,231.0,Spanish,2.000000,2009.0,8.2,33000,18.167424
2551,104,Guillermo del Toro,406.0,37.623143,Drama|Fantasy|War,Ivana Baquero,Pan's Labyrinth,467234,1083.0,Spanish,13.500000,2006.0,8.2,27000,24.123143
2047,107,Hayao Miyazaki,212.0,4.710455,Adventure|Animation|Family|Fantasy,Christian Bale,Howl's Moving Castle,214091,330.0,Japanese,24.000000,2004.0,8.2,13000,-19.289545
3553,109,José Padilha,142.0,0.008060,Action|Crime|Drama|Thriller,Wagner Moura,Elite Squad,81644,107.0,Portuguese,4.000000,2007.0,8.1,11000,-3.991940
3423,112,Katsuhiro Ôtomo,150.0,0.439162,Action|Animation|Sci-Fi,Mitsuo Iwata,Akira,106160,430.0,Japanese,1100.000000,1988.0,8.1,0,-1099.560838
2914,123,Je-kyu Kang,86.0,1.110186,Action|Drama|War,Min-sik Choi,Tae Guk Gi: The Brotherhood of War,31943,224.0,Korean,12.800000,2004.0,8.1,0,-11.689814
4461,125,Thomas Vinterberg,98.0,1.647780,Drama,Ulrich Thomsen,The Celebration,65951,258.0,Danish,1.300000,1998.0,8.1,5000,0.347780
4267,147,Alejandro G. Iñárritu,157.0,5.383834,Drama|Thriller,Adriana Barraza,Amores Perros,173551,361.0,Spanish,2.000000,2000.0,8.1,11000,3.383834
2830,152,Alejandro Amenábar,157.0,2.086345,Biography|Drama|Romance,Belén Rueda,The Sea Inside,64556,140.0,Spanish,10.000000,2004.0,8.1,0,-7.913655
4284,157,Ari Folman,231.0,2.283276,Animation|Biography|Documentary|Drama|History|War,Ari Folman,Waltz with Bashir,46107,156.0,Hebrew,1.500000,2008.0,8.0,0,0.783276
3456,163,Vincent Paronnaud,242.0,4.443403,Animation|Biography|Drama|War,Catherine Deneuve,Persepolis,70194,158.0,French,7.300000,2007.0,8.0,14000,-2.856597
3344,166,Karan Johar,210.0,4.018695,Adventure|Drama|Thriller,Shah Rukh Khan,My Name Is Khan,69759,235.0,Hindi,12.000000,2010.0,8.0,27000,-7.981305
4897,182,Sergio Leone,122.0,3.500000,Action|Drama|Western,Clint Eastwood,A Fistful of Dollars,147566,235.0,Italian,0.200000,1964.0,8.0,0,3.300000
4144,200,Walter Salles,71.0,5.595428,Drama,Fernanda Montenegro,Central Station,28951,257.0,Portuguese,2.900000,1998.0,8.0,0,2.695428
3264,206,Michael Haneke,447.0,0.225377,Drama|Romance,Isabelle Huppert,Amour,70382,190.0,French,8.900000,2012.0,7.9,33000,-8.674623
2863,208,Clint Eastwood,251.0,13.753931,Drama|History|War,Yuki Matsuzaki,Letters from Iwo Jima,132149,316.0,Japanese,19.000000,2006.0,7.9,5000,-5.246069
2605,211,Ang Lee,287.0,128.067808,Action|Drama|Romance,Chen Chang,"Crouching Tiger, Hidden Dragon",217740,1641.0,Mandarin,15.000000,2000.0,7.9,0,113.067808
3510,227,Yash Chopra,29.0,2.921738,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119.0,Hindi,7.000000,2004.0,7.9,2000,-4.078262
4415,238,Fabián Bielinsky,94.0,1.221261,Crime|Drama|Thriller,Ricardo Darín,Nine Queens,38215,125.0,Spanish,1.500000,2000.0,7.9,0,-0.278739
3677,241,Christophe Barratier,112.0,3.629758,Drama|Music,Jean-Baptiste Maunier,The Chorus,44151,110.0,French,5.500000,2004.0,7.9,0,-1.870242
2493,242,Yimou Zhang,283.0,0.084961,Action|Adventure|History,Jet Li,Hero,149414,841.0,Mandarin,31.000000,2002.0,7.9,0,-30.915039
4640,246,Cristian Mungiu,233.0,1.185783,Drama,Anamaria Marinca,"4 Months, 3 Weeks and 2 Days",44763,172.0,Romanian,0.590000,2007.0,7.9,14000,0.595783

**Checkpoint 3:** Can you spot `Veer-Zaara` in the dataframe?

- ### Subtask 3.5: Find the best directors

    1. Group the dataframe using the `director_name` column.
    2. Find out the top 10 directors for whom the mean of `imdb_score` is the highest and store them in a new dataframe `top10director`.

In [26]:
# Write your code for extracting the top 10 directors here
grouped_directors = movies.groupby('director_name') #Gropuing data on basis of director_name
list_of_Top_Direc = grouped_directors.imdb_score.mean().sort_values(ascending = False).head(10)
#Sorting based on imbd_score mean() of direcors and getting top 10 rows having directors
top10director = pd.DataFrame(list_of_Top_Direc) #making dataframe after getting top 10 directors based on imdb_score
top10director

                   imdb_score
director_name
Charles Chaplin      8.600000
Tony Kaye            8.600000
Ron Fricke           8.500000
Damien Chazelle      8.500000
Majid Majidi         8.500000
Alfred Hitchcock     8.500000
Sergio Leone         8.433333
Christopher Nolan    8.425000
Asghar Farhadi       8.400000
Richard Marquand     8.400000

**Checkpoint 4:** No surprises that `Damien Chazelle` (director of Whiplash and La La Land) is in this list.

-  ### Subtask 3.6: Find popular genres

You might have noticed the `genres` column in the dataframe with all the genres of the movies seperated by a pipe (`|`). Out of all the movie genres, the first two are most significant for any film.

1. Extract the first two genres from the `genres` column and store them in two new columns: `genre_1` and `genre_2`. Some of the movies might have only one genre. In such cases, extract the single genre into both the columns, i.e. for such movies the `genre_2` will be the same as `genre_1`.
2. Group the dataframe using `genre_1` as the primary column and `genre_2` as the secondary column.
3. Find out the 5 most popular combo of genres by finding the mean of the gross values using the `gross` column and store them in a new dataframe named `PopGenre`.

In [27]:
# Write your code for extracting the first two genres of each movie here

movies['genre_1'] = movies['genres'].apply(lambda x:x.split('|')[0])
# Getting first genre into genere_1 by splitting data of each and every value using apply() and split()
movies['genre_2'] = movies['genres'].apply(lambda x: x.split("|")[0] if len(x.split('|'))<2 else x.split("|")[1])
#Here we check each and every value has two values or not, it not take first value else second value

In [28]:
# Write your code for grouping the dataframe here
movies_by_segment = grouped_DF_OnGenres = movies.groupby(['genre_1','genre_2']) #Grouping based on genre_1,genre_2

In [37]:
# Write your code for getting the 5 most popular combo of genres here
Top_5_Genre_Combo = movies_by_segment['gross'].mean().sort_values(ascending = False).head(5)
# Calculating mean and sorting data based on that mean and assiging top 5 rows to new variable
Combo_Genre = list(Top_5_Genre_Combo.index) #Getting combo genres

PopGenre = pd.DataFrame(list(Top_5_Genre_Combo),index=Combo_Genre,columns=['Combo_of_Genre_Mean'])
#Creating new dataframe PopGenre with mean values with index as Combo_Genres
PopGenre

                        Combo_of_Genre_Mean
(Family, Sci-Fi)                 434.949459
(Adventure, Sci-Fi)              228.627758
(Adventure, Family)              118.919540
(Adventure, Animation)           116.998550
(Action, Adventure)              109.595465

**Checkpoint 5:** Well, as it turns out. `Family + Sci-Fi` is the most popular combo of genres out there!

-  ### Subtask 3.7: Find the critic-favorite and audience-favorite actors

    1. Create three new dataframes namely, `Meryl_Streep`, `Leo_Caprio`, and `Brad_Pitt` which contain the movies in which the actors: 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' are the lead actors. Use only the `actor_1_name` column for extraction. Also, make sure that you use the names 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' for the said extraction.
    2. Append the rows of all these dataframes and store them in a new dataframe named `Combined`.
    3. Group the combined dataframe using the `actor_1_name` column.
    4. Find the mean of the `num_critic_for_reviews` and `num_user_for_review` and identify the actors which have the highest mean.

In [38]:
# Write your code for creating three new dataframes here

Meryl_Streep = movies[movies.actor_1_name == 'Meryl Streep']# Including all movies in which Meryl_Streep is the lead by indexing

In [39]:
Leo_Caprio = movies[movies.actor_1_name == 'Leonardo DiCaprio']# Including all movies in which Leo_Caprio is the lead by indexing

In [40]:
Brad_Pitt = movies[movies.actor_1_name == 'Brad Pitt']# Including all movies in which Brad_Pitt is the lead by indexing

In [41]:
# Write your code for combining the three dataframes here
Combined = Meryl_Streep.append(Leo_Caprio).append(Brad_Pitt)
# Appending three data frames into one using append() along axis = 0 by default

In [42]:
# Write your code for grouping the combined dataframe here
Grouping_Combined = Combined.groupby('actor_1_name') #Grouping Combined data on basis of 'actor_1_name' using groupby()

In [43]:
# Write the code for finding the mean of critic reviews and audience reviews here
Calculated_Mean = Grouping_Combined['num_critic_for_reviews','num_user_for_reviews'].mean()
#Calculating Mean for two columns on grouped data
print(Calculated_Mean,end="\n\n")

print("The actors which have the highest mean.")
Calculated_Mean.sort_values(['num_critic_for_reviews','num_user_for_reviews'],ascending=[0,0]).head(1)
#This command shows Highest actor by sorting ascending(0->False) for two columns on basis of reviews

                   num_critic_for_reviews  num_user_for_reviews
actor_1_name
Brad Pitt                      245.000000            742.352941
Leonardo DiCaprio              330.190476            914.476190
Meryl Streep                   181.454545            297.181818

The actors which have the highest mean.

                   num_critic_for_reviews  num_user_for_reviews
actor_1_name
Leonardo DiCaprio              330.190476             914.47619

**Checkpoint 6:** `Leonardo` has aced both the lists!